apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: myimage=avaeusk8sacrpoc.azurecr.io/react-svc
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/myimage.pull-secret: pullsecret:argocd/image-pull-secrets
    argocd-image-updater.argoproj.io/myimage.allow-tags: regexp:^[0-9]{2,3}
    argocd-image-updater.argoproj.io/myimage.update-strategy: name
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/Velmani-Jayavel/reactapp.git
    targetRevision: main
    path: image-updater/frontend
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
